### ISSUE TITLE
CAMEL Questions & Clarification

### ISSUE THREAD

**Issue by notu-ngoctrung** [ThoroughImages/CAMEL#6]
Hi!
Thank you so much for the paper and dataset. I'm currently implementing CAMEL following the procedure in the paper and I have some unclear thoughts, hoping you could help me clarify those.

1. About Max-Max & Max-Min, since they focus on the cancerous prediction of patches within an image, I select the appropriate patch, for each image, for the backprop by only considering the max/ min value of cancerous outputs from the model (e.g. I have 2 patches with NC-CA predictions from the model are (0.4, 0.6) and (0.2, 0.7) --> I choose the second patch for backprop). I wonder if this is a reasonable implementation or is there anything misunderstood?
2. In the paper, you mentioned at the end of 3.1.1 section that "Noted that we discard those potentially confusing samples whose predicted labels are different from their corresponding image-level labels." I infer that they are those with NC labels but predicted as CA. Could you please explain a bit more on what "confusing samples" mean?
3. I wonder if instance-level labels are the same as patch-level labels (i.e. we split an image into several smaller patches (e.g. 320x320))?

Looking forward to your reply. Thank you!

**Comment by physicso** [comment]
Thank you very much for your interest in our work. Hope the following information accelarate your research.

1. NC CA
1) 0.4 0.6
2) 0.3 0.7
If max-max & label == 0 -> 2)
If max-max & label == 1 -> 2)
If max-min & label == 0 -> 1)
If max-min & label == 1 -> 2)

2. If the image label is CA, we choose all the instances with predicted labels CA and NC since CA images contain both instances. Otherwise, for NC images, we discard all the instances predicted as CA. 

3. The instance-level labels are the same as patch-level ones. The "instance" is used following the basic theory of multiple instance learning (MIL).

**Comment by physicso** [comment]
Thank you very much for your interest in our work. Hope the following information accelerate your research.

1. NC CA
1) 0.4 0.6
2) 0.3 0.7
If max-max & label == 0 -> 2)
If max-max & label == 1 -> 2)
If max-min & label == 0 -> 1)
If max-min & label == 1 -> 2)

2. If the image label is CA, we choose all the instances with predicted labels CA and NC since CA images contain both instances. Otherwise, for NC images, we discard all the instances predicted as CA. 

3. The instance-level labels are the same as patch-level ones. The "instance" is used following the basic theory of multiple instance learning (MIL).

**Comment by notu-ngoctrung** [comment]
Thank you so much for the answers! It's clear to me now.

Just another point I hope to clarify: regarding label enrichment performance of cMIL models, did you use ResNet-50 architecture for the baseline model (FSB)?

**Comment by physicso** [comment]
Yes!

**Comment by notu-ngoctrung** [comment]
I get it now.
Thank you and have a nice day!
